# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'Run npm test'
  inputs:
    command: custom
    verbose: false
    customCommand: 'test'

- task: Npm@1
  displayName: 'Run npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      dist/**
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: ons-fe/metherton_frontend_packages
